#!/bin/sh

docker run  \
    -d \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.config:/config \
    -v `pwd`:/work \
    -v $HOME/.gitconfig:/devhome/.gitconfig \
    --device /dev/dri \
    -e DISPLAY=$DISPLAY \
    -e HOSTUSER=`id -un` \
    -e HOSTGROUP=`id -gn` \
    -e HOSTUSERID=`id -u` \
    -e WORKSPACE=`pwd` \
    ulrichschreiner/atocker "$@"
